### PR TITLE
Simplify run command, small spelling fixes

### PR DESCRIPTION
**Pull request by pavlo-v-chernykh**
You can run program using `cargo run` command.
Small spelling fixes.

### CODE REVIEW

**Comment by pillserg** [comment]
As I recall cargo run handles cmd line args purly. thats why direct run.

**Comment by pavlo-v-chernykh** [comment]
I have no issues with `cargo run --` approach.
Please, specify which issues you have been faced with.

**Comment by pillserg** [comment]
Will check it at home and return to you. Maybe its nothing.

**Comment by pavlo-v-chernykh** [comment]
Looking forward to hearing more details :8ball:

**Comment by pillserg** [comment]
ok i just overlooked "--" feature

**Pull request merged**
